name: Lint

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run lint
      - run: npm run format:check
